---
title: "Interaction Partner Identity Ratings"
author: "Annika Richter"
date: "2026-06-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
```

# How well did participants acutally detect whether they were interacting with a human or an AI chatbot? 
```{r}
# Load Interleaf data
df <- read.csv("../../Data/df_interleaf_measures.csv")
```

```{r}
# How many ratings were actually extreme enough, that they can be interpreteted as "confident human" or "confident AI?"
df <- df %>%
  mutate(
    confidence_interaction_partner = case_when(
      ai_detection_rating <= 25 ~ "human",       # confident "human"
      ai_detection_rating >= 75 ~ "ai",          # confident "AI"
      TRUE            ~ "uncertain"     # 26–74, the middle
    )
  )
```

```{r}
# Truth in certain ratings
conf <- df %>%
  filter(confidence_interaction_partner != "uncertain") %>%
  mutate(
    truth_ai    = shared_condition_order == "with_ai",
    response_ai = confidence_interaction_partner == "ai",
    correct     = response_ai == truth_ai
  )

mean(conf$correct) # overall accuracy on confident judgments

conf %>% # split out: better at spotting AI or humans?
  group_by(shared_condition_order) %>%
  summarise(n = n(), accuracy = mean(correct))
```

```{r}
library(ggplot2)
library(tidyverse)

teal <- "#0397b2"
damped_light_blue <- "#b6e2ff"

colors <- c("with_ai" = teal, "without_ai" = damped_light_blue)
```

```{r}
p_ai_detection <- df %>%
  ggplot(aes(x = ai_detection_rating, 
             y = shared_condition_order)) +
  geom_jitter(aes(color = shared_condition_order), 
              height = 0.15, size = 2.5, alpha = 0.6) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black", linewidth = 0.5) +
  geom_vline(xintercept = 100, linetype = "dotted", color = "black", linewidth = 0.5) +
  geom_vline(xintercept = 25, linetype = "dotted", color = "black", linewidth = 0.5) +
  geom_vline(xintercept = 75, linetype = "dotted", color = "black", linewidth = 0.5) +
  scale_color_manual(values = colors) +
  scale_x_continuous(
    limits = c(-1, 105),
    breaks = c(0, 25, 75, 100),
    labels = c("Definitely\nHuman", "25", "75", "Definitely\nAI")
  ) +
  scale_y_discrete(labels = c("with_ai" = "human-AI", "without_ai" = "human-human"),
                   expand = expansion(add = 0.8)) +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 18) +
  theme(
    axis.text = element_text(size = 16, color = "black"),
    legend.position = "none",
    panel.grid = element_blank(),
    axis.line.x = element_line(color = "black"),
    axis.ticks.x = element_line(color = "black")
  )

p_ai_detection
```
```{r}
ggsave("ai_detection_plot.pdf", p_ai_detection,
       width = 10, height = 4, dpi = 300, bg = "white", device = pdf)
```
